version: '3.7'

services:
  raven1:
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:38888:38888"
    env_file:
      - raven.env
    volumes:
      - type: bind
        source: .\volumes\config1
        target: /opt/RavenDB/config
      - type: bind
        source: .\volumes\data1
        target: /opt/RavenDB/Server/RavenData
  raven2:
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "127.0.0.2:8081:8081"
      - "127.0.0.2:38888:38888"
    env_file:
      - raven.env
    volumes:
      - type: bind
        source: .\volumes\config2
        target: /opt/RavenDB/config
      - type: bind
        source: .\volumes\data2
        target: /opt/RavenDB/Server/RavenData
  raven3:
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "127.0.0.3:8081:8081"
      - "127.0.0.3:38888:38888"
    env_file:
      - raven.env
    volumes:
      - type: bind
        source: .\volumes\config3
        target: /opt/RavenDB/config
      - type: bind
        source: .\volumes\data3
        target: /opt/RavenDB/Server/RavenData