version: '3.7'

services:
  ravendb-A:
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - raven.env
    volumes:
      - type: bind
        source: .\volumes\config-a
        target: /opt/RavenDB/config
      - type: bind
        source: .\volumes\data-a
        target: /opt/RavenDB/Server/RavenData
  ravendb-B:
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - raven.env
    volumes:
      - type: bind
        source: .\volumes\config-b
        target: /opt/RavenDB/config
      - type: bind
        source: .\volumes\data-b
        target: /opt/RavenDB/Server/RavenData